apiVersion: v1
data:
  nginx.conf: |-
    user  nginx;
    worker_processes  1;
    error_log  /var/log/nginx/error.log warn;
    pid        /var/run/nginx.pid;
    events {
      worker_connections  1024;
    }
    http {
      include       /etc/nginx/mime.types;
      default_type  application/octet-stream;
      log_format  main  '$remote_addr - $remote_user [$time_local] "$request" '
                        '$status $body_bytes_sent "$http_referer" '
                        '"$http_user_agent" "$http_x_forwarded_for"';
      access_log  /var/log/nginx/access.log  main;
      sendfile        on;
      keepalive_timeout  65;
      server {
        listen       8080;
        server_name  localhost;
        location / {
          root   /app;
          index  index.html;
          try_files $uri $uri/ /index.html;
        }
        error_page   500 502 503 504  /50x.html;
        location = /50x.html {
          root   /usr/share/nginx/html;
        }
      }
    }
kind: ConfigMap
metadata:
  name: root-ui-nginx-configmap-57tgccdd86
---
apiVersion: v1
kind: Service
metadata:
  name: ui-root
spec:
  ports:
  - name: http
    port: 80
    protocol: TCP
    targetPort: nginx-http
  selector:
    app: ui-root
  type: NodePort
---
apiVersion: apps/v1
kind: Deployment
metadata:
  labels:
    app: ui-root
    version: b7fb2da
  name: ui-root-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ui-root
  template:
    metadata:
      labels:
        app: ui-root
        version: b7fb2da
    spec:
      containers:
      - image: eu.gcr.io/vote-of-confidence-233210/voc-ui-root:b7fb2da
        name: ui-root
        ports:
        - containerPort: 8080
          name: nginx-http
        resources:
          requests:
            cpu: 50m
        volumeMounts:
        - mountPath: /etc/nginx
          name: config-volume
          subPath: nginx.conf
      volumes:
      - configMap:
          name: root-ui-nginx-configmap-57tgccdd86
        name: config-volume
